spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      fail-on-unknown-properties: false

app:
  encryption:
    key: ${ENCRYPTION_KEY}